//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G5_Website_giay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietDatHang
    {
        public int OrderID { get; set; }
        public int spID { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual Orderpro Orderpro { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
