//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G5_Website_giay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderpro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orderpro()
        {
            this.chitietDatHangs = new HashSet<chitietDatHang>();
        }
    
        public int OrderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> khID { get; set; }
        public Nullable<int> nvID { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietDatHang> chitietDatHangs { get; set; }
        public virtual khachHang khachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
