//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G5_Website_giay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.chitietDatHangs = new HashSet<chitietDatHang>();
        }
    
        public int spID { get; set; }
        public string spName { get; set; }
        public string spMieuta { get; set; }
        public Nullable<System.DateTime> spNgaySanXuat { get; set; }
        public string lspID { get; set; }
        public string nhasanxuatID { get; set; }
        public Nullable<decimal> gia { get; set; }
        public string Images { get; set; }
        public Nullable<int> Size { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietDatHang> chitietDatHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}
